---
# Source: extraction-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment 
metadata
  name: data-format-hub
  namespace: ar
spec:
  selector:
    matchLabels:
      app: data-format-hub
      replica: blue
  replicas: 1 
  template:
    metadata:
      labels:
        app: data-format-hub
        replica: blue
    spec:
      containers:
        - name: data-format-hub
          image: .dkr.ecr.us-east-1.amazonaws.com/docker:data-format-hub_20240625_v1.0.23   
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:           
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "200Mi"