name: AR-data-format-hub Actions
on: workflow_dispatch   # [push, workflow_dispatch]

env:
  AWS_REGION: us-east-1
permissions:
  contents: write

jobs: 

  Python_Build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
          current_date : $(date +'%Y%m%d')
          echo "current_date: ${current_date}"
